version: '3.7'

services:

  pyme:
    build: .
    command: ["python", "mercadolibre/pyme.py"]
    volumes:
      - .:/code
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - USER_ID=${USER_ID}
      - ITEM_ID=${ITEM_ID}
      - QUESTION_ID=${QUESTION_ID}